version: "3"
services:
        db:
                image: "postgres"
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: postgres
                        POSTGRES_DB: main_site
                ports:
                  - 8080:5432
                volumes:
                        - ./postgres-data:/var/lib/postgresql/data/ # persist data even when container shuts down
